version: '3'
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: always
    # ports:
    #   - "1433:1433"
    environment:
      SA_PASSWORD: "S3cur3PssW0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
  app:
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - "5000:80"